apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - name: goapp
        image: jancunha/argocd-go:v1
        ports:
        - containerPort: 8080
